version: '3'

services:
  sandbox-ui:
    image: clinia/sandbox-ui
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - npm_token
    ports:
      - "3000:3000"


secrets:
  npm_token:
    environment: NPM_TOKEN